### ISSUE TITLE
A question about single LSTM

### ISSUE THREAD

**Issue by kylecat2015** [ArrasL/LRP_for_LSTM#1]
Hello, I try to write a LRP for single LSTM, I found that the relevance focus on the first sequence. Just like this,
![image](https://user-images.githubusercontent.com/10059654/45992061-5ce8a280-c0ba-11e8-980d-83b7b361f8f6.png)
I don't think that the first sequence is more important. Could you please expain it?
Thank you~

**Comment by ArrasL** [comment]
Have a look at the [hints](https://github.com/ArrasL/LRP_for_LSTM/blob/master/DOC.md) to adapt the code to a unidirectional LSTM.
