### ISSUE TITLE
error for run for first line 

### ISSUE THREAD

**Issue by Sandy4321** [ArrasL/LRP_for_LSTM#3]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6b89fdf70eda> in <module>()
----> 1 from code.LSTM.LSTM_bidi import *
      2 from code.util.heatmap import html_heatmap
      3 
      4 import codecs
      5 import numpy as np

ModuleNotFoundError: No module named 'code.LSTM'; 'code' is not a package

**Comment by ArrasL** [comment]
You may append the current working directory to the PYTHONPATH to find the module like this:
`export PYTHONPATH=$PYTHONPATH:$pwd`
