### ISSUE TITLE
no colores for heatmap in web based demo  as shown in paper

### ISSUE THREAD

**Issue by Sandy4321** [ArrasL/LRP_for_LSTM#4]
![image](https://user-images.githubusercontent.com/11426119/46262005-3dda7e00-c4c9-11e8-9af0-ff6553328135.png)

**Comment by ArrasL** [comment]
It seems GitHub does not render Jupyter Notebook files correctly (see [here](https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/)).
You can copy the notebook URL into [nbviewer](https://nbviewer.jupyter.org/) to render it correctly.
