### ISSUE TITLE
can we train bidirectional model?

### ISSUE THREAD

**Issue by akshayuppal3** [ArrasL/LRP_for_LSTM#6]
is it possible to train the bilsmt mode, does it require changing the model file with new weights?

**Comment by ArrasL** [comment]
Hi,

Yes you can train the bi-LSTM model with whatever neural network toolbox you like (Tensorflow, Pytorch, Keras, Dynet...).

Then you just need to save the trained model's weights as numpy arrays to use the LRP code (and check the ordering of the gates in your weights to make them compatible with the LRP code, here are some [hints](https://github.com/ArrasL/LRP_for_LSTM/blob/master/DOC.md) how to do this).

**Comment by akshayuppal3** [comment]
Also what happens if I think of changing the classes to binary intstead of multiclass?

**Comment by ArrasL** [comment]
Binary classification is just a special case of multiclass classification. So there is nothing you need to care about or change in the code if you want to apply it to a binary prediction task (the number of classes is not hard coded).

Just save your weights in a python dict of numpy arrays (akin `model` in the  `__init__`  method of the class `LSTM_bidi`). The input, hidden layer and output dimensions will then be inferred from the weights' shapes.

Typically, the only places where you need to adapt the code, will be the  `__init__` and `set_input`methods, where you load your trained model, and define the input sequence `x` (`x_rev`).
The other methods don't need to be changed, if your model is a standard LSTM.
