### ISSUE TITLE
Can you please define the train() function for LSTM_bidi class?

### ISSUE THREAD

**Issue by sharan21** [ArrasL/LRP_for_LSTM#7]
The current class only supports loading of pretrained models and I am having a little trouble changing the __init__ and implementing the train() function to train this model from scratch.

Thanks,
Sharan

**Comment by ArrasL** [comment]
Indeed I don't provide any training code to train an LSTM.

For this you can check out any neural network toolbox of your choice.
Here is for example a Pytorch tutorial:
[https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html](https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html)
(Github: [https://github.com/pytorch/tutorials/blob/master/beginner_source/nlp/sequence_models_tutorial.py](https://github.com/pytorch/tutorials/blob/master/beginner_source/nlp/sequence_models_tutorial.py))
For Tensorflow:
[https://www.tensorflow.org/tutorials/text/text_classification_rnn](https://www.tensorflow.org/tutorials/text/text_classification_rnn)
(Github: [https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/text_classification_rnn.ipynb](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/text_classification_rnn.ipynb))

Once you trained the LSTM model, you just need to pack your model weights into Numpy arrays, then you can use the `LRP_for_LSTM`code to explain its decisions.
